[server]
domain = localhost
root_url = http://localhost:3000

[auth.anonymous]
enabled = false
# enabled = true  # для тестового режима, не блокировать вход

[log]
level = info
mode = console file
file = /var/log/grafana/grafana.log